# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: Tropical
version: '0.0.0'
github: "ferynando7/Tropical"
license: MIT
author: "Fernando Zhapa"
maintainer: "Fernando Zhapa"
# synopsis: A new Haskeleton package.
# description: Tropical is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - containers
  - numeric-prelude
  - semiring-simple
  - algebra
  - singletons
  extra-deps:
  source-dirs: library


  haddock: true
  haddock-arguments:
    haddock-args:     # Additional arguments passed to haddock, --haddock-arguments
      - "--latex"
    # haddock-args:
    # - "--css=/home/user/my-css"
  open-haddocks: false    # --open
  haddock-deps: true     # if unspecified, defaults to true if haddock is set
  haddock-internal: true


executables:
  Tropical:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - Tropical
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  Tropical-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - Tropical
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  Tropical-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - Tropical
    - tasty
    - tasty-hspec
    - tasty-hunit
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
